/*
 * routes/+layout.ts
 * This file is used to configure the SvelteKit application layout.
 * This is generated by the SvelteKit CLI when creating this project.
 */

// Tauri doesn't have a Node.js server to do proper SSR
// so we use adapter-static with a fallback to index.html to put the site in SPA mode
export const ssr = false;
